### PR TITLE
Libcanard v2.0

### LINKED ISSUE #168: Support dual TX queues for redundant transports
I already have this implemented in a private fork; the implementation should be ported upstream but it would probably require a major version bump due to the slight API change.

### LINKED ISSUE #175: Typical usage of the library should not require casting away const qualifiers
@thirtytwobits says:

> the `CanardTransfer` payload is `const void*` but is <...> used to free the payload when you are done with it. This leads to `const_cast<void*>(transfer->payload)` in C++ which is not something you ever want to see. `const` is part of the API so if you violate the constness you are, technically, entering undefined behaviour.

to which I say:

>This is a known issue, yes: https://github.com/UAVCAN/libcanard/blob/2a116170285fb47fcaae150ad21c2ccde0756a5f/libcanard/canard.h#L251-L252
>The reason the deallocation function accepts a mutable `void*` is because the `free()`  from the standard library is defined this way.
>We could make it `const void*` but then if you are using the standard heap or pretty much any other heap manager implemented in C (like o1heap), you will have to cast away your const anyway before calling the deallocation function.
>Making `o1heapFree()` accept a const void would require it to cast away the const also because it has to mutate the returned memory fragment.

Fixing this requires breaking API changes so it is postponed until v2.0.

### LINKED ISSUE #176: Examples given in the README should use Nunavut-generated types
This manually-serialized instance of `uavcan.primitive.String` should be replaced with autogenerated struct in order to make the intended usage patterns clearer:

image

### LINKED ISSUE #178: build check error: narrowing conversion from 'int' to signed type 'int8_t' (aka 'signed char') is implementation-defined
image
image
image

### PR DESCRIPTION
**Pull request by pavel-kirienko**
- Closes #168 
- Fixes #175 
- Closes #176 -- while the demos that are shown in the README still don't use Nunavut, they are explicit about it.
- Closes #178 by removing the offending code (use Nunavut instead)

See the changelog in the README for a brief overview of the changes. The most interesting changes are two:

- Split API into smaller entities to improve its orthogonality and fix the problem of const correctness reported by Scott.
- Replace all linked lists with AVL trees to reduce the asymptotic complexity of both RX and TX pipelines from linear to logarithmic.

@coderkalyan do you want to include #171 into this release or should we wait for v2.1?

### CODE REVIEW

**Comment by coderkalyan** [comment]
And I'll review the rest of this soon as well :)

File: libcanard/canard.h [hunk 1]
```diff
@@ -245,54 +232,111 @@ typedef struct
...
+    /// on an ad-hoc basis when we first receive a transfer from that node. This is O(1) because our memory
+    /// allocation routines are assumed to be O(1) and we make at most one allocation per remote node.
     ///
-    /// A far more predictable and a much simpler approach is to pre-allocate states here statically instead of keeping
+    /// A more predictable and simpler approach is to pre-allocate states here statically instead of keeping
     /// just pointers, but it would push the size of this instance from about 0.5 KiB to ~3 KiB for a typical 32-bit
     /// system. Since this is a general-purpose library, we have to pick a middle ground so we use the more complex
     /// but more memory-efficient approach.
-    struct CanardInternalRxSession* _sessions[CANARD_NODE_ID_MAX + 1U];
+    struct CanardInternalRxSession* sessions[CANARD_NODE_ID_MAX + 1U];  ///< Read-only DO NOT MODIFY THIS
```
Comment (PetervdPerk-NXP) [inline libcanard/canard.h:323]: Regarding @thirtytwobits statement
> I'll keep reading but why are we giving up on 4k RAM?

Would utilizing CAVL here save enough memory to support 4KB RAM targets?
The maximum number of sessions is 128 thus would give you at most 7 hops in a binary tree.
Didn't look into the specifics of CAVL yet, but I suppose it's more memory efficient then allocating 128 pointers.

Comment (pavel-kirienko) [reply libcanard/canard.h:323]: >The maximum number of sessions is 128 thus would give you at most 7 hops in a binary tree.

10 hops in the worst case (the upper bound is a bit more involved than log2(size))

>Didn't look into the specifics of CAVL yet, but I suppose it's more memory efficient then allocating 128 pointers.

This is true. From the time complexity perspective though, CAVL is less desirable because O(1) array lookup is much easier to analyze and validate than O(log n) tree search. We can certainly go this way but should we really?
